In [28]:
import cv2
image=cv2.imread("galaxy.jpg",0)
print(image)
print(type(image))
print(image.shape)
print(image.ndim)
print(image.size)
resize_image=cv2.resize(image,(495,495),dst=1,fx=495,fy=495)
cv2.imshow("Galaxy",resize_image)
cv2.imwrite("Galaxy_imagen_cuadrada.jpg", resize_image)
cv2.waitKey(0)
cv2.destroyAllWindows()



[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]
<class 'numpy.ndarray'>
(1485, 990)
2
1470150
